import express from 'express';
import cors from 'cors';
import dotenv from 'dotenv';
import authRoutes from './routes/authRoutes.js';
import aiRoutes from './routes/aiRoutes.js';
import jobRoutes from './routes/jobRoutes.js';
import { seedDatabase } from './database/seed.js';

dotenv.config();
const app=express();
const PORT=process.env.PORT||5000;
const allowedOrigins=(process.env.FRONTEND_ORIGIN||'http://localhost:5173').split(',').map(value=>value.trim());
app.disable('x-powered-by');
app.set('trust proxy',process.env.TRUST_PROXY==='true'?1:false);
app.use(cors({origin:(origin,callback)=>!origin||allowedOrigins.includes(origin)?callback(null,true):callback(new Error('Origin not allowed')),credentials:true}));
app.use(express.json({limit:'1mb'}));
app.get('/api/health',(req,res)=>res.json({status:'online',service:'Campus to Corporate AI Employability Backend API',version:'2.0.0',timestamp:new Date().toISOString()}));
app.use('/api/auth',authRoutes);
app.use('/api/ai',aiRoutes);
app.use('/api',jobRoutes);
app.use((err,req,res,next)=>{console.error('Unhandled Server Error:',err.message);res.status(500).json({success:false,error:'Internal Server Error'});});
await seedDatabase();
app.listen(PORT,()=>console.log(`Campus to Corporate Backend Server: http://localhost:${PORT}/api/health`));
