import { useState } from 'react';
import { reviewResume } from '../services/gemini';
const API_BASE=import.meta.env.VITE_API_BASE_URL||'http://localhost:5000/api';
export default function ResumeEnhancer({studentProfile}){
 const[text,setText]=useState(studentProfile?.resumeText||'');const[result,setResult]=useState(null);const[loading,setLoading]=useState(false);const[fileLoading,setFileLoading]=useState(false);const[error,setError]=useState('');
 const review=async()=>{setLoading(true);setError('');setResult(await reviewResume(text,studentProfile?.targetRole||'Software Engineer'));setLoading(false);};
 const parsePdf=async event=>{const file=event.target.files?.[0];if(!file)return;setFileLoading(true);setError('');try{const form=new FormData();form.append('resume',file);const response=await fetch(`${API_BASE}/ai/parse-resume`,{method:'POST',body:form,credentials:'include'});const data=await response.json();if(!response.ok||!data.success)throw new Error(data.error||'Could not parse the PDF.');setText(data.data.text);setResult(null);}catch(e){setError(e.message);}finally{setFileLoading(false);}};
 return <div className="space-y-5"><div><h2 className="text-3xl font-bold">Resume AI</h2><p className="text-slate-500">Upload a PDF or paste your resume and get an ATS-focused review.</p></div><div className="rounded-2xl border bg-white p-5"><label className="text-sm font-semibold">Resume PDF</label><input type="file" accept="application/pdf" onChange={parsePdf} disabled={fileLoading} className="mt-2 block w-full text-sm"/><p className="text-xs text-slate-500 mt-2">PDF only, maximum 5 MB.</p></div><textarea rows="12" value={text} onChange={e=>setText(e.target.value)} className="w-full rounded-2xl border bg-white p-5" placeholder="Paste your resume text here"/>{error&&<p className="rounded-lg bg-red-50 p-3 text-sm text-red-700">{error}</p>}<button onClick={review} disabled={loading||!text.trim()} className="rounded-lg bg-indigo-600 px-5 py-3 text-white">{loading?'Reviewing...':'Review resume'}</button>{result&&<div className="rounded-2xl border bg-white p-6"><p className="text-sm text-slate-500">ATS score</p><p className="text-4xl font-bold">{result.atsScore}/100</p><p className="mt-3">Formatting: {result.formattingRating}</p><p className="mt-3 text-sm">Missing keywords: {(result.missingKeywords||[]).join(', ')||'None identified'}</p></div>}</div>;
}
